name: jeeth_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  pin_code_fields: ^8.0.1
  flutter_svg: ^1.1.1+1
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.7
  provider: ^6.0.3
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  firebase_messaging: 
  flutter_local_notifications: 
  firebase_core: ^2.8.0
  image_picker: ^0.8.3+3
  email_validator: ^2.0.1
  url_launcher: ^6.0.9
  flutter_html: ^3.0.0-alpha.5
  google_maps_flutter:
  geolocator: ^10.0.1
  permission_handler: ^10.4.5
  razorpay_flutter: ^1.3.0
  # badges: ^2.0.3
  otp_autofill: ^2.1.0
  cached_network_image: ^3.2.2
  # path_provider: ^2.0.11
  # video_compress: ^3.1.2
  # video_player: ^2.4.5
  # chewie: ^1.2.2
  # share: ^2.0.4
  firebase_dynamic_links: ^5.3.6
  # barcode_scan: ^3.0.0
  barcode_widget: ^2.0.4
  share_plus: 
  animated_size_and_fade: ^3.0.1
  app_settings:
  file_picker: ^5.5.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgIcons/
    - assets/placeholders/

 
  fonts:
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Light.ttf
          weight: 300
        - asset: assets/fonts/Blinker-Regular.ttf
          weight: 400
        - asset: assets/fonts/Blinker-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Blinker-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
